version: '3.7'
services:
    database:
        image: 'mysql:8.0'
        container_name: api_mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: api
        ports:
            - '3306'
        volumes:
          - mysql_db:/var/lib/mysql
        networks:
          - back

    phpmyadmin:
        image: phpmyadmin:5.1
        container_name: api_pma
        restart: always
        ports:
          - 8080:80
        environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=mysql
        volumes:
          - pma_data:/var/www/html
        networks:
          - back
        depends_on:
          - database

networks:
    back:

volumes:
    mysql_db:

    pma_data:
